server:
  port: 6060
spring:
  datasource:
    driverClassName: org.h2.Driver
    username: user
    password: password
    url: jdbc:h2:mem:championdb
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
    generate-ddl: false
    defer-datasource-initialization: true
  h2:
    console.enabled: true
springdoc:
  api-docs:
    enabled: true
    path: /api-docs