INSERT INTO PARTICIPANTS (NAME, MAIL) VALUES ('M.Ismail', 'm.ismail@m.com');
INSERT INTO PARTICIPANTS (NAME, MAIL) VALUES ('A.Amr', 'a.amr@m.com');
INSERT INTO PARTICIPANTS (NAME, MAIL) VALUES ('M.Khaled', 'm.khaled@m.com');
INSERT INTO PARTICIPANTS (NAME, MAIL) VALUES ('Omar', 'omar@m.com');
INSERT INTO PARTICIPANTS (NAME, MAIL) VALUES ('M.Galal', 'm.galal@m.com');
INSERT INTO PARTICIPANTS (NAME, MAIL) VALUES ('Galala', 'galala@m.com');
INSERT INTO PARTICIPANTS (NAME, MAIL) VALUES ('M.Yehia', 'm.yehia@m.com');
INSERT INTO PARTICIPANTS (NAME, MAIL) VALUES ('A.Amry', 'a.amry@m.com');
INSERT INTO PARTICIPANTS (NAME, MAIL) VALUES ('A.Khaled', 'a.khaled@m.com');
INSERT INTO PARTICIPANTS (NAME, MAIL) VALUES ('Amry', 'amry@m.com');
INSERT INTO PARTICIPANTS (NAME, MAIL) VALUES ('M.Ziton', 'm.ziton@m.com');

